---
- name: Download Epel repository for centos/redhat 6
  get_url: url=http://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm dest=/tmp/epel-release-latest-6.noarch.rpm
  when: "ansible_os_family" == 'RedHat' and ansible_distribution_major_version == '6'"

- name: Install Epel repo which we just downloaded in the above step
  command: rpm -ivh /tmp/epel-release-latest-6.noarch.rpm creates=/etc/yum.repos.d/epel.repo
  when: "ansible_os_family" == 'RedHat' and ansible_distribution_major_version == '6'"

- name: Download EPEL Repo - Centos/RHEL 7
  get_url: url=http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm dest=/tmp/epel-release-latest-7.noarch.rpm
  when: "ansible_or_family" == 'RedHat' and ansible_distribution_major_version == '7'"

- name: Install the EPEL Repo - Centos/RHEL 7
  command: rpm -ivh /tmp/epel-release-latest-7.noarch.rpm creates=/etc/yum.repos.d/epel.repo
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version =='7'"

- name: Install Libselinux-python
  yum: name=libselinux-python
   
